spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

app:
  frontend-url: ${FRONTEND_URL}

cors:
  allowed-origins:
    - ${FRONTEND_URL}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}